name: Dispatch Terraspace
on:
  workflow_dispatch:
    inputs:
      env:
        description: "TS_ENV"
        type: choice
        default: prod
        options: # Add more environment if needed
          - dev
          - prod
      command:
        description: "Terraspace command to run"
        default: "plan demo"
jobs:
  run:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      #TS_ENV: ${{ github.event.inputs.env }}
      #TS_TOKEN: ${{ secrets.TS_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Install Terraspace
      run:
        .github/bin/install

    - name: Run Terraspace
      run: |
        terraspace ${{ github.event.inputs.command }} -y
